name: scribble
description: "A simple notes app"
publish_to: 'none' 

version: 3.0.0+6

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.1.1
  google_fonts: ^6.1.0
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.20.0 
  hive_flutter: ^1.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  flutter_slidable: ^4.0.0
  lottie: ^3.1.3
  share_plus: ^12.0.0
  sqflite: ^2.4.2
  path: ^1.9.1
  stream_transform: ^2.1.1
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

  flutter_lints: ^6.0.0
 
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/icons/ 
    - assets/lottie/
   
